CREATE TABLE users(user_id SERIAL PRIMARY KEY,
            username VARCHAR (50) NULL,
            email VARCHAR (355) UNIQUE NULL,
            created_on TIMESTAMP without time zone  NULL,
            last_login TIMESTAMP without time zone,
            user_image VARCHAR (100)  NULL,
            device_type VARCHAR (50)  NULL,
            device_id VARCHAR (100)  NULL,
            device_name VARCHAR (100)  NULL,
            last_visited_screen JSON  NULL,
            phone_no VARCHAR (30) UNIQUE NOT NULL)
