service: spot-me-lambdas-test-service

plugins:
  - serverless-webpack

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: '../../webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
  package:
    individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId
  vpcConfig:
    SecurityGroupIds: [sg-07a2e6b0fda5038c6]
    SubnetIds: [subnet-03c21dcb77f11aff5, subnet-0234adab8f86d8656, subnet-07b0f604ba9a9aec4, subnet-0d0d9bd7032a1c7e3]
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
        - s3:DeleteObjects
        - s3:PutObjectAcl
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      "Resource": "*"
  environment:
    MONGODB_URI: mongodb://spotmeroot:spotmeroot@dev-spot-me-docdb-instance.cdnduxceh2ya.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0
    stage: ${self:custom.stage}
functions:
  test:
    handler: handler.testFunction
    events:
      - http:
          path: /test/test-function
          method: get
          cors: true
    vpcConfig:
      vpc: vpc-054ee8f04e7c9e7dd
      SecurityGroupIds: sg-07a2e6b0fda5038c6
      SubnetIds: 
        - subnet-03c21dcb77f11aff5
        - subnet-0234adab8f86d8656
        - subnet-07b0f604ba9a9aec4
        - subnet-0d0d9bd7032a1c7e3