service: the-labz-dynamodb

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    dev: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.dev}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

resources:
  Resources:
    ProjectsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stage}-Projects
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
    InvitesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stage}-Invites
        KeySchema:
          - AttributeName: projectId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: projectId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
        GlobalSecondaryIndexes:
          - IndexName: userIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.tableThroughput}
              WriteCapacityUnits: ${self:custom.tableThroughput}
  Outputs:
    ProjectsTableArn:
      Value:
        Fn::GetAtt:
          - ProjectsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ProjectsTableArn

    ProjectsTableName:
      Value:
        Ref: ProjectsTable
      Export:
        Name: ${self:custom.stage}-ProjectsTable

    InvitesTableArn:
      Value:
        Fn::GetAtt:
          - InvitesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-InvitesTableArn

    InvitesTableName:
      Value:
        Ref: InvitesTable
      Export:
        Name: ${self:custom.stage}-InvitesTable
